---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heap
  labels:
    app: sorting
    cheese: heap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorting
      task: heap
  template:
    metadata:
      labels:
        app: sorting
        task: heap
        version: v0.0.1
    spec:
      containers:
      - name: heap
        image: andriimaslianko/heap:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: heap
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: sorting
    task: heap