---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merge
  labels:
    app: sorting
    cheese: merge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorting
      task: merge
  template:
    metadata:
      labels:
        app: sorting
        task: merge
        version: v0.0.1
    spec:
      containers:
      - name: merge
        image: andriimaslianko/algo-sorting-merge
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: merge
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: sorting
    task: merge