---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick
  labels:
    app: sorting
    cheese: quick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorting
      task: quick
  template:
    metadata:
      labels:
        app: sorting
        task: quick
        version: v0.0.1
    spec:
      containers:
      - name: quick
        image: andriimaslianko/algo-sorting-quick
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quick
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: sorting
    task: quick