---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selection
  labels:
    app: sorting
    cheese: selection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorting
      task: selection
  template:
    metadata:
      labels:
        app: sorting
        task: selection
        version: v0.0.1
    spec:
      containers:
      - name: selection
        image: andriimaslianko/algo-sorting-selection
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: selection
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: sorting
    task: selection