---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: sorting
    cheese: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorting
      task: api
  template:
    metadata:
      labels:
        app: sorting
        task: api
        version: v0.0.1
    spec:
      containers:
      - name: api
        image: andriimaslianko/api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionString.mongo
          value: "mongodb://mongo-0.mongo:27017"
        - name: database
          value: "sorting"
        - name: collection
          value: "results"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: sorting
    task: api